name: largenetvis
channels:
  - anaconda
  - defaults
dependencies:
  - flask=2.0.3
  - jinja2=3.0.3
  - pandas
  - joblib=1.0.1=pyhd3eb1b0_0
  - networkx=2.7.1
  - python-louvain=0.15
  - scikit-learn
  - scipy
  - sqlalchemy
